export {default as NavBar} from '../Components/NavBar'
export {default as ProjectsContent} from '../Components/ProjectsContent'
export {default as Home} from '../Components/Home'
export {default as About} from '../app/about/page'
export {default as Projects} from '../app/projects/page'
export {default as Button} from '../Components/Button'
export {default as ProjectData} from './ProjectData'