import { Metadata } from "next";
import AdminProvider from "./_components/AdminProvider";
import AdminSideBar from "./_components/AdminSideBar";

interface AdminLayoutProps {
  children: React.ReactNode;
}
export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};
const AdminLayout = ({ children }: AdminLayoutProps) => {
  return (
    <AdminProvider>
      <div className="flex gap-2 relative min-h-[100vh]">
        <div className="h-full w-[60px] relative">
          <AdminSideBar />
        </div>
        {children}
      </div>
    </AdminProvider>
  );
};

export default AdminLayout;
